name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-core-and-native:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check the package.json of /core to see if it has changed
        uses: EndBug/version-check@v1.3.0
        with:
          file-name: core/package.json
          diff-search: true
        id: core-version-change

      - name: Check the package.json of /native to see if it has changed
        uses: EndBug/version-check@v1.3.0
        with:
          file-name: native/package.json
          diff-search: true
        id: native-version-change

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://npm.pkg.github.com/
          scope: '@birdiecare'

      - name: Install common dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NPM_REGISTRY_TOKEN" >> .npmrc
        env:
          NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
          NODE_ENV: development

      - name: Build core
        working-directory: core
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NPM_REGISTRY_TOKEN" >> .npmrc
          npm ci
          npm run build
        env:
          NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
          NODE_ENV: development
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy core
        if: steps.core-version-change.outputs.changed == 'true'
        working-directory: core
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and deploy native
        if: steps.native-version-change.outputs.changed == 'true'
        working-directory: native
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NPM_REGISTRY_TOKEN" >> .npmrc
          npm ci
          npm run build
          npm publish
        env:
          NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
          NODE_ENV: development
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
