name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-core-and-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://npm.pkg.github.com/
          scope: '@birdiecare'

      - name: Install common dependencies
        run: yarn install

      - name: Build and deploy core
        run: |
          cd core
          yarn install
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and deploy native
        run: |
          cd native
          yarn install
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
