name: CI

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install

      - name: Run core tests & build for native tests
        run: | 
          cd core 
          yarn install
          npm test
          npm run build

      - name: Native Tests
        run: | 
          cd native
          yarn install
          npm test
          cd ..
